name: cobmo
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - attrs=21.4.0
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.5.18.1
  - cairo=1.16.0
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - cfitsio=4.1.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - contextily=1.2.0
  - cryptography=37.0.2
  - curl=7.83.1
  - cvxpy=1.2.1
  - cvxpy-base=1.2.1
  - cycler=0.11.0
  - ecos=2.0.10
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - intel-openmp=2022.1.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9e
  - kealib=1.4.14
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.10
  - libffi=3.4.2
  - libgdal=3.4.3
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=14.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.5.2
  - mercantile=1.2.1
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.4.2
  - pcre=8.45
  - pillow=9.1.1
  - pip=22.1.1
  - pixman=0.40.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.3
  - proj=9.0.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - qdldl-python=0.1.5
  - rasterio=1.2.10
  - requests=2.27.1
  - scipy=1.8.1
  - scs=3.2.0
  - setuptools=62.3.2
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.38.5
  - tbb=2021.5.0
  - tiledb=2.8.3
  - tk=8.6.12
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.4.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - atomicwrites==1.4.0
    - bleach==5.0.0
    - bokeh==2.4.3
    - colorcet==3.0.0
    - coverage==6.4
    - dynaconf==3.1.8
    - flake8==4.0.1
    - gurobipy==9.5.1
    - h5py==3.6.0
    - holoviews==1.14.9
    - hvplot==0.8.0
    - importlib-metadata==4.11.4
    - iniconfig==1.1.1
    - jinja2==3.1.2
    - kaleido==0.2.1
    - markdown==3.3.7
    - markupsafe==2.1.1
    - mccabe==0.6.1
    - multimethod==1.8
    - panel==0.13.0
    - param==1.12.1
    - parameterized==0.8.1
    - plotly==5.8.0
    - pluggy==1.0.0
    - psychrolib==2.5.0
    - pvlib==0.9.1
    - py==1.11.0
    - pycodestyle==2.8.0
    - pyct==0.4.8
    - pyflakes==2.4.0
    - pytest==7.1.2
    - pytest-cov==3.0.0
    - pytest-subtests==0.7.0
    - pyviz-comms==2.2.0
    - pyyaml==6.0
    - tenacity==8.0.1
    - tomli==2.0.1
    - tornado==6.1
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - webencodings==0.5.1
    - zipp==3.8.0
