name: Documentation

on: [push]

jobs:
  build-documentation:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Fetch all repository branches and tags
      run: |
        git fetch --prune --unshallow
    - name: Set up Python
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        conda install sphinx
        pip install -r docs/requirements.txt
    - name: Build documentation HTML with Sphinx
      run: |
        sphinx-multiversion docs docs/_build/html
        cp docs/assets/gh-pages_index.html docs/_build/html/index.html
        find docs/_build/html -type f -name "*.html" -exec sed -i 's/<li><p>\(.*\)<\/p>\(.*\)/<li>\1\2/g' {} +
    - name: Deploy documentation HTML to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html/
        keep_files: false
