name: Python tests

on: [push]

jobs:
  run-tests:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [
            windows-latest,
            # macos-latest,
            ubuntu-latest
        ]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -v -e .
    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. Line lengths should not exceed 120 characters.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests
